#!/bin/bash
# Script to commit the refactoring changes

echo "Files to be committed:"
echo "====================="
echo ""
echo "New/Modified Files:"
echo "- pyproject.toml (new) - Package configuration"
echo "- CLAUDE.md (modified) - Updated with refactoring status"
echo "- README_endopoint.md (new) - Package documentation"
echo "- REFACTORING_SUMMARY.md (new) - Detailed summary of changes"
echo ""
echo "Package Structure:"
echo "- src/endopoint/ - New package directory"
echo "  - utils/ - I/O, logging, RNG utilities"
echo "  - datasets/ - Dataset adapter protocol and implementations"
echo "  - geometry/ - Canvas and coordinate transforms"
echo "  - prompts/ - Prompt builders and registry"
echo "  - models/ - LLM model adapters"
echo "  - data/ - Presence cache implementation"
echo "  - eval/ - JSON parser"
echo ""
echo "CLI Tools:"
echo "- cli/build_presence_cache.py - Cache building CLI"
echo ""
echo "Configs:"
echo "- configs/dataset_cholecseg8k.yaml"
echo "- configs/dataset_endoscape.yaml"
echo ""
echo "To commit these changes manually, run:"
echo ""
echo "git add pyproject.toml CLAUDE.md README_endopoint.md REFACTORING_SUMMARY.md"
echo "git add src/endopoint/"
echo "git add cli/"
echo "git add configs/*.yaml"
echo ""
echo "git commit -m \"refactor: Transform research code into modular endopoint package"
echo ""
echo "Major changes:"
echo "- Create proper Python package structure with pyproject.toml"
echo "- Implement DatasetAdapter protocol for multi-dataset support"
echo "- Add ModelAdapter protocol for LLM models (OpenAI, Anthropic, Google)"
echo "- Extract geometry, prompts, and data processing into modules"
echo "- Add CLI tools starting with build_presence_cache"
echo "- Make all algorithms K-agnostic (not hardcoded to 12 organs)"
echo "- Add deterministic caching with proper versioning"
echo ""
echo "This implements the first phase of the refactoring plan in"
echo "claude_code_commands/01-refactor-code.md. The package maintains"
echo "backward compatibility while providing a cleaner foundation for"
echo "future development."
echo ""
echo "See REFACTORING_SUMMARY.md for detailed changes and usage instructions.\""